version: "3.4"

services:
  web:
    ports:
      - "1339:80"
    volumes:
      - '../services/auth/src:/src:delegated'
      - './nginx.conf:/etc/nginx/nginx.conf'

  phpfpm:
    volumes:
      - '../services/auth/src:/src'